# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True, verbose_name=b'hover\xe5\x90\x8d\xe7\xa7\xb0')),
                ('vector', models.CharField(max_length=100, null=True, verbose_name=b'\xe5\x90\x91\xe9\x87\x8f/\xe4\xbd\x8d\xe7\xbd\xae')),
                ('transition', models.CharField(max_length=300, null=True, verbose_name=b'\xe8\xbd\xac\xe5\x9c\xba\xe5\x8a\xa8\xe4\xbd\x9c')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.CharField(default=uuid.uuid1, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SceneSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_name', models.CharField(max_length=20, null=True, verbose_name=b'\xe7\xa9\xba\xe9\x97\xb4\xe5\x90\x8d\xe7\xa7\xb0')),
                ('ordinal', models.PositiveSmallIntegerField(default=1, verbose_name=b'\xe5\xba\x8f\xe5\x8f\xb7')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='panorama.Scene', verbose_name=b'\xe5\x9c\xba\xe6\x99\xaf')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('logo', models.ImageField(upload_to=b'seller-logo/')),
                ('phone', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('desc', models.CharField(max_length=300, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=100)),
                ('cache_url', models.CharField(max_length=100, null=True)),
                ('thumb_url', models.CharField(max_length=100, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='panorama.Seller', verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe8\x80\x85')),
            ],
        ),
        migrations.CreateModel(
            name='Texture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.SmallIntegerField(choices=[(1, b'\xe5\xa3\x81\xe7\xba\xb8'), (2, b'\xe5\x9c\xb0\xe6\x9d\xbf'), (3, b'\xe7\x93\xb7\xe7\xa0\x96'), (4, b'\xe6\x9d\xbf\xe6\x9d\x90'), (5, b'\xe5\xb8\x83\xe6\x96\x99')], default=None, null=True)),
                ('url', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=30)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='panorama.Space', verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe7\xa9\xba\xe9\x97\xb4')),
            ],
        ),
        migrations.AddField(
            model_name='scenespace',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='panorama.Space', verbose_name=b'\xe7\xa9\xba\xe9\x97\xb4'),
        ),
        migrations.AddField(
            model_name='scene',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='panorama.Space', verbose_name=b'\xe5\x85\xa5\xe5\x8f\xa3\xe7\xa9\xba\xe9\x97\xb4'),
        ),
        migrations.AddField(
            model_name='scene',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='panorama.Seller', verbose_name=b'\xe5\x95\x86\xe6\x88\xb7'),
        ),
        migrations.AddField(
            model_name='hot',
            name='scene_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='panorama.SceneSpace', verbose_name=b'\xe5\x9c\xba\xe6\x99\xaf'),
        ),
    ]
